[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  headers = {  Content-Type = "text/event-stream"}
  to = "/.netlify/functions/api/:splat"
[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/event-stream"